export const BOOKING_SHEAT_REQUEST = "@@BOOKINGSHEATREDUCER/BOOKING_SHEAT_REQUEST"
export const BOOKING_SHEAT_SUCCESS = "@@BOOKINGSHEATREDUCER/BOOKING_SHEAT_SUCCESS"
export const BOOKING_SHEAT_FAIL = "@@BOOKINGSHEATREDUCER/BOOKING_SHEAT_FAIL"
