export const HOME_CAROUSEL_REQUEST = "@@CAROUSELREDUCER/HOME_CAROUSEL_REQUEST"
export const HOME_CAROUSEL_SUCCESS = "@@CAROUSELREDUCER/HOME_CAROUSEL_SUCCESS"
export const HOME_CAROUSEL_FAIL = "@@CAROUSELREDUCER/HOME_CAROUSEL_FAIL"

export const HOME_THEATER_REQUEST = "@@THEATERREDUCER/HOME_THEATER_REQUEST"
export const HOME_THEATER_SUCCESS = "@@THEATERREDUCER/HOME_THEATER_SUCCESS"
export const HOME_THEATER_FAIL = "@@THEATERREDUCER/HOME_THEATER_FAIL"

export const HOME_THEATER_ADDRESS_REQUEST = "@@THEATERADDRESSREDUCER/HOME_THEATER_ADDRESS_REQUEST"
export const HOME_THEATER_ADDRESS_SUCCESS = "@@THEATERADDRESSREDUCER/HOME_THEATER_ADDRESS_SUCCESS"
export const HOME_THEATER_ADDRESS_FAIL = "@@THEATERADDRESSREDUCER/HOME_THEATER_ADDRESS_FAIL"

export const HOME_THEATER_MOVIE_REQUEST = "@@THEATERMOVIEREDUCER/HOME_THEATER_MOVIE_REQUEST"
export const HOME_THEATER_MOVIE_SUCCESS = "@@THEATERMOVIEREDUCER/HOME_THEATER_MOVIE_SUCCESS"
export const HOME_THEATER_MOVIE_FAIL = "@@THEATERMOVIEREDUCER/HOME_THEATER_MOVIE_FAIL"

export const MOVIE_REQUEST = `@@LISTMOVIEREDUCER/MOVIE_REQUEST` 
export const MOVIE_SUCCESS = `@@LISTMOVIEREDUCER/MOVIE_SUCCESS` 
export const MOVIE_FAIL = `@@LISTMOVIEREDUCER/MOVIE_FAIL` 

export const MOVIEITEM_REQUEST = `@@MOVIEITEMDETAILREDUCER/MOVIEITEM_REQUEST`
export const MOVIEITEM_SUCCESS = `@@MOVIEITEMDETAILREDUCER/MOVIEITEM_SUCCESS`
export const MOVIEITEM_FAIL = `@@MOVIEITEMDETAILREDUCER/MOVIEITEM_FAIL`


export const AUTH_REQUEST = "@@AUTHREDUCER/AUTH_REQUEST"
export const AUTH_SUCCESS = "@@AUTHREDUCER/AUTH_SUCCESS"
export const AUTH_FAIL = "@@AUTHREDUCER/AUTH_FAIL"

// export const BOOKING_SHEAT_REQUEST = "@@QuanLyDatVeReducer/BOOKING_SHEAT_REQUEST"
// export const BOOKING_SHEAT_SUCCESS = "@@QuanLyDatVeReducer/BOOKING_SHEAT_SUCCESS"
// export const BOOKING_SHEAT_FAIL = "@@QuanLyDatVeReducer/BOOKING_SHEAT_FAIL"

export const ROOM_TICKET_DETAIL_REQUEST = "@@QuanLyDatVeReducer/ROOM_TICKET_DETAIL_REQUEST"
export const ROOM_TICKET_DETAIL_SUCCESS = "@@QuanLyDatVeReducer/ROOM_TICKET_DETAIL_SUCCESS"
export const ROOM_TICKET_DETAIL_FAIL = "@@QuanLyDatVeReducer/ROOM_TICKET_DETAIL_FAIL"

export const REGISTER_REQUEST = "@@REGISTERREDUCER/REGISTER_REQUEST"
export const REGISTER_SUCCESS = "@@REGISTERREDUCER/REGISTER_SUCCESS"
export const REGISTER_FAIL = "@@REGISTERREDUCER/REGISTER_FAIL"

export const SEAT_DATA = "@@seatReducer/SEAT_DATA"