export const HOME_CAROUSEL_REQUEST = "@@CAROUSELREDUCER/HOME_CAROUSEL_REQUEST"
export const HOME_CAROUSEL_SUCCESS = "@@CAROUSELREDUCER/HOME_CAROUSEL_SUCCESS"
export const HOME_CAROUSEL_FAIL = "@@CAROUSELREDUCER/HOME_CAROUSEL_FAIL"

export const HOME_THEATER_REQUEST = "@@THEATERREDUCER/HOME_THEATER_REQUEST"
export const HOME_THEATER_SUCCESS = "@@THEATERREDUCER/HOME_THEATER_SUCCESS"
export const HOME_THEATER_FAIL = "@@THEATERREDUCER/HOME_THEATER_FAIL"