export const MOVIEITEM_REQUEST = `@@MOVIEITEMDETAILREDUCER/MOVIEITEM_REQUEST`
export const MOVIEITEM_SUCCESS = `@@MOVIEITEMDETAILREDUCER/MOVIEITEM_SUCCESS`
export const MOVIEITEM_FAIL = `@@MOVIEITEMDETAILREDUCER/MOVIEITEM_FAIL`