export const HOME_CAROUSEL_REQUEST = "@@CAROUSELREDUCER/HOME_CAROUSEL_REQUEST"
export const HOME_CAROUSEL_SUCCESS = "@@CAROUSELREDUCER/HOME_CAROUSEL_SUCCESS"
export const HOME_CAROUSEL_FAIL = "@@CAROUSELREDUCER/HOME_CAROUSEL_FAIL"

export const HOME_THEATER_REQUEST = "@@THEATERREDUCER/HOME_THEATER_REQUEST"
export const HOME_THEATER_SUCCESS = "@@THEATERREDUCER/HOME_THEATER_SUCCESS"
export const HOME_THEATER_FAIL = "@@THEATERREDUCER/HOME_THEATER_FAIL"

export const HOME_THEATER_ADDRESS_REQUEST = "@@THEATERADDRESSREDUCER/HOME_THEATER_ADDRESS_REQUEST"
export const HOME_THEATER_ADDRESS_SUCCESS = "@@THEATERADDRESSREDUCER/HOME_THEATER_ADDRESS_SUCCESS"
export const HOME_THEATER_ADDRESS_FAIL = "@@THEATERADDRESSREDUCER/HOME_THEATER_ADDRESS_FAIL"

export const HOME_THEATER_MOVIE_REQUEST = "@@THEATERMOVIEREDUCER/HOME_THEATER_MOVIE_REQUEST"
export const HOME_THEATER_MOVIE_SUCCESS = "@@THEATERMOVIEREDUCER/HOME_THEATER_MOVIE_SUCCESS"
export const HOME_THEATER_MOVIE_FAIL = "@@THEATERMOVIEREDUCER/HOME_THEATER_MOVIE_FAIL"

export const MOVIE_REQUEST = `@@LISTMOVIEREDUCER/MOVIE_REQUEST` 
export const MOVIE_SUCCESS = `@@LISTMOVIEREDUCER/MOVIE_SUCCESS` 
export const MOVIE_FAIL = `@@LISTMOVIEREDUCER/MOVIE_FAIL` 